In [5]:
from PIL import Image
from astropy.io import fits
import numpy as np

In [6]:
# Arguments
folder = '20241107'
image_list = [f'{folder}/image/IMG_{i:04d}_reduced.fits' for i in range(246, 257)]
print(image_list)


['20241107/image/IMG_0246_reduced.fits', '20241107/image/IMG_0247_reduced.fits', '20241107/image/IMG_0248_reduced.fits', '20241107/image/IMG_0249_reduced.fits', '20241107/image/IMG_0250_reduced.fits', '20241107/image/IMG_0251_reduced.fits', '20241107/image/IMG_0252_reduced.fits', '20241107/image/IMG_0253_reduced.fits', '20241107/image/IMG_0254_reduced.fits', '20241107/image/IMG_0255_reduced.fits', '20241107/image/IMG_0256_reduced.fits']


In [9]:
def fits2bmp(image_name):
    # Load the image
    image = fits.open(image_name)[0].data
    print(image.shape)
    # Save the image as a PNG
    # Convert from 16-bit linear to 8-bit gamma=2.2
    image = ((image / 65535.0) ** (1/2.2)) * 255
    image = np.clip(image, 0, 255).astype(np.uint8)
    # Move the color axis to the last dimension
    image = np.moveaxis(image, 0, -1)
    print(image[100,100])
    image = Image.fromarray(image)
    image.save(f'{image_name[:-5]}.bmp')

In [10]:
for image_name in image_list:
    fits2bmp(image_name)

(3, 2000, 3000)
[178 173 173]
(3, 2000, 3000)
[147 164 172]
(3, 2000, 3000)
[145 120 165]
(3, 2000, 3000)
[173 138 166]
(3, 2000, 3000)
[110 135 145]
(3, 2000, 3000)
[140 136 155]
(3, 2000, 3000)
[139 144 182]
(3, 2000, 3000)
[137 129 162]
(3, 2000, 3000)
[137 116 178]
(3, 2000, 3000)
[137 129 150]
(3, 2000, 3000)
[138 152 149]
